export const GET_SUBSCRIPTION_PRODUCTS = "GET_SUBSCRIPTION_PRODUCTS";
export const GET_SUBSCRIPTION_PRODUCTS_SUCCESS =
  "GET_SUBSCRIPTION_PRODUCTS_SUCCESS";
export const GET_SUBSCRIPTION_PRODUCTS_FAILED =
  "GET_SUBSCRIPTION_PRODUCTS_FAILED";

export const CREATE_USER_SUBSCRIPTION = "CREATE_USER_SUBSCRIPTION";
export const CREATE_USER_SUBSCRIPTION_SUCCESS =
  "CREATE_USER_SUBSCRIPTION_SUCCESS";
export const CREATE_USER_SUBSCRIPTION_FAILED =
  "CREATE_USER_SUBSCRIPTION_FAILED";

export const OPEN_SUBSCRIPTION_MODAL = "OPEN_SUBSCRIPTION_MODAL";
export const OPEN_SUBSCRIPTION_MODAL_SUCCESS =
  "OPEN_SUBSCRIPTION_MODAL_SUCCESS";

export const GET_SUBSCRIPTIONS_LIST = "GET_SUBSCRIPTIONS_LIST";
export const GET_SUBSCRIPTIONS_LIST_SUCCESS = "GET_SUBSCRIPTIONS_LIST_SUCCESS";
export const GET_SUBSCRIPTIONS_LIST_FAILED = "GET_SUBSCRIPTIONS_LIST_FAILED";

export const OPEN_CANCEL_SUBSCRIPTION_MODAL = "OPEN_CANCEL_SUBSCRIPTION_MODAL";
export const OPEN_UPDATE_SUBSCRIPTION_MODAL = "OPEN_UPDATE_SUBSCRIPTION_MODAL";

export const CANCEL_USER_SUBSCRIPTION = "CANCEL_USER_SUBSCRIPTION";
export const CANCEL_USER_SUBSCRIPTION_SUCCESS =
  "CANCEL_USER_SUBSCRIPTION_SUCCESS";
export const CANCEL_USER_SUBSCRIPTION_FAILED =
  "CANCEL_USER_SUBSCRIPTION_FAILED";

export const GET_SUBSCRIPTION_ITEM_BY_ID = "GET_SUBSCRIPTION_ITEM_BY_ID";
export const GET_SUBSCRIPTION_ITEM_BY_ID_SUCCESS =
  "GET_SUBSCRIPTION_ITEM_BY_ID_SUCCESS";
export const GET_SUBSCRIPTION_ITEM_BY_ID_FAILED =
  "GET_SUBSCRIPTION_ITEM_BY_ID_FAILED";

export const UPDATE_USER_SUBSCRIPTION = "UPDATE_USER_SUBSCRIPTION";
export const UPDATE_USER_SUBSCRIPTION_SUCCESS =
  "UPDATE_USER_SUBSCRIPTION_SUCCESS";
export const UPDATE_USER_SUBSCRIPTION_FAILED =
  "UPDATE_USER_SUBSCRIPTION_FAILED";
